# -*- coding: utf-8 -*-
"""Amazon Best Seller.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOm5rYnHeIUZ1TKM1exFyv1rp6iUpsB6
"""



import pandas as pd

df=pd.read_csv('/content/bestsellers.csv')

df.head()

df.info()

df.isnull().sum()

df.shape

df.nunique()

"""We have duplicates values so we should remove."""

df.drop_duplicates(inplace=True)

"""Rename Columns"""

df.rename(columns={'User Rating':'User_Rating', 'Year': 'Publication Year', 'User Rating': 'Rating'},inplace=True)

df['Price']= df['Price'].astype(float)

author_count= df['Author'].value_counts()
print(author_count)

avg_rating_by_genre= df.groupby('Genre')['Rating'].mean()
print(avg_rating_by_genre)

author_count.head(10).to_csv('author_count.csv')
avg_rating_by_genre.to_csv('avg_rating_by_genre.csv')
